services:
  adform-sql-api:
    image: ${DOCKER_REGISTRY-}adformsqlapi
    build:
      context: .
      dockerfile: AdForm-SQL-API/Dockerfile
    ports:
      - "5000:5000"
      - "5001:5001"
  postgresdb:
    image: postgres:latest
    container_name: postgresdb
    restart: always
    ports:
      - "5432:5432"
    environment:
        POSTGRES_DB: AdFormSQL
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: admin
    volumes:
      - AdForm_PostgrSQL_SQL_volume:/var/lib/postgresql/data
volumes:
    AdForm_PostgrSQL_SQL_volume:
        external: true